### ISSUE TITLE
Upgrading Angular latest version

### ISSUE THREAD

**Issue by Krivobarac** [Romko775/ng-moment-timezone-picker#49] opened 2021-08-02 08:06 UTC
Hi, Are you planning upgrade to latest Angular version?

**Comment by Romko775** [comment] 2021-08-02 08:13
Hi @Krivobarac !
Thank you for you message. Will update as soon as possible when I will be free :)

Cheers :)

**Comment by Krivobarac** [comment] 2021-08-02 08:24
thanks for quick response :)

**Comment by Romko775** [comment] 2021-08-07 12:11
Duplicate of https://github.com/Romko775/ng-moment-timezone-picker/issues/32

**Closed as completed by Romko775** 2021-08-07 12:11 UTC
